# Generated by Django 3.2.12 on 2022-10-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orden_ordenitem_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orden'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.producto'),
        ),
    ]
